# Artificial Neural Network

### Importing the libraries

In [21]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [22]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [23]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [25]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [27]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

ColumnTransformer, sklearn kütüphanesinde bulunan bir sınıftır ve makine öğrenimi projelerinde sütun (kolon) bazında dönüşümler uygulamak için kullanılır. Bu sınıf, farklı sütunlara farklı dönüşümler uygulamak ve ardından bu dönüşümleri birleştirmek için kullanışlıdır.
ColumnTransformer sınıfı, bu dönüşümleri belirli sütunlara uygulamak için kullanılır. Örnekteki transformers parametresi, dönüşümün adını ('encoder') ve hangi dönüşümün uygulanacağını (OneHotEncoder) belirtir. [1] ise dönüşümün hangi sütuna uygulanacağını belirtir. Burada, 1. sütuna (indeksleme 0'dan başladığı için) OneHotEncoder dönüşümü uygulanacaktır. Yani, bu sütun kategorik bir sütundur ve One-Hot Encoding işlemi uygulanarak kategorik değerler sayısal değerlere dönüştürülecektir.

remainder parametresi ise dönüşüm uygulanmayan sütunların ne yapılacağını belirtir. 'passthrough' değeri, dönüşüm uygulanmayan sütunların doğrudan geçirileceği anlamına gelir. Yani, dönüşüm uygulanmayan sütunlar için herhangi bir işlem yapılmaz ve veri setinde aynı şekilde kalır.

Sonuç olarak, ColumnTransformer sınıfı, birden fazla sütuna farklı dönüşümler uygulamak ve bu dönüşümleri birleştirmek için kullanılır. Örnekteki ColumnTransformer nesnesi, One-Hot Encoding dönüşümünü belirli bir sütuna uygularken diğer sütunları olduğu gibi bırakır. Böylece, veri kümesi farklı dönüşümler uygulanarak makine öğrenimi algoritması için uygun hale getirilir.

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [29]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [32]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

Bu kod, Keras kütüphanesinde tanımlanmış bir yapay sinir ağı modeli olan "ann" modeline, yeni bir yoğun katman (Dense layer) ekler. Eklenen katman, 6 adet nöron içerir ve bu nöronlar, ReLU (Rectified Linear Unit) olarak adlandırılan aktivasyon fonksiyonunu kullanır.

Yoğun katman, yapay sinir ağı modellerinde en sık kullanılan katman türlerinden biridir. Bu katman, önceki katmandaki tüm nöronlarla bağlantılıdır ve her bir nöron, girdi özellikleriyle ağırlıklarını çarparak bir çıktı değeri üretir. Bu çıktı değerleri, sonraki katmana aktarılır ve bu işlem, modelin çıktısına kadar devam eder.

ReLU aktivasyon fonksiyonu, en yaygın kullanılan aktivasyon fonksiyonlarından biridir ve genellikle yapay sinir ağı modellerindeki performansı arttırır. ReLU, negatif girdilerin çıktısını sıfır yaparken, pozitif girdilerin aynı şekilde aktarılmasını sağlar. Bu nedenle, modelin daha doğru sonuçlar vermesine yardımcı olabilir.

In [33]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [34]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

Bu kod, "ann" modeline bir başka yoğun katman daha ekler. Eklenen katman, sadece 1 adet nöron içerir ve bu nöron, sigmoid olarak adlandırılan aktivasyon fonksiyonunu kullanır.

Sigmoid fonksiyonu, girdileri 0 ile 1 arasında bir değere dönüştüren bir aktivasyon fonksiyonudur. Bu fonksiyon, genellikle ikili sınıflandırma problemlerinde kullanılır, çünkü sigmoid fonksiyonunun çıktısı, 0.5'in altında veya üstünde olup olmadığına bağlı olarak, sınıflandırılan örneğin pozitif veya negatif olarak etiketlenmesine karar vermek için kullanılabilir.

Yani, eklenen bu son yoğun katman, modelin ikili sınıflandırma problemleri için kullanılmasını sağlar. Sigmoid fonksiyonu, aynı zamanda çıktı değerlerinin olasılık değerlerine dönüştürülmesine de yardımcı olabilir, bu da modelin tahminlerini yorumlamayı daha kolay hale getirir.

In [35]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN


Bu kod, "ann" modelinin derlenmesini sağlar. Derleme, modelin eğitim için hazır hale getirilmesini sağlar.

Parametrelerin anlamları:

"optimizer": Modelin optimize edilmesi için kullanılacak algoritmayı belirtir. "adam" optimizer, stokastik gradyan inişi algoritması (SGD) temelli bir optimizerdir ve genellikle birçok makine öğrenmesi uygulamasında iyi sonuçlar verir.
"loss": Modelin kayıp fonksiyonunu belirtir. Binary cross-entropy kaybı, ikili sınıflandırma problemleri için yaygın olarak kullanılan bir kayıp fonksiyonudur.
"metrics": Modelin performansını ölçmek için kullanılacak metrikleri belirtir. Bu örnekte, sınıflandırma doğruluğu (accuracy) kullanılır.
"ann" modeli bu şekilde derlenince, artık eğitim işlemine başlamak için hazır hale gelir. Eğitim sürecinde, model, verilen eğitim verilerine göre optimize edilir ve en uygun ağırlık değerleri bulunmaya çalışılır. Bu, modelin daha sonra test verileri üzerinde iyi bir performans göstermesini sağlar.

In [36]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

epochs, modelin tüm eğitim verilerini kaç kez göreceği sayısını ifade eder. Bir epoch, tüm eğitim verilerinin bir kez işlenmesine denk gelir. Daha fazla epoch, modelin daha fazla eğitim verisiyle çalışmasına ve daha iyi sonuçlar elde etmesine yardımcı olabilir. Ancak aşırı öğrenme (overfitting) riski de artabilir.

batch_size, eğitim sırasında verilerin küçük gruplara bölünmesini sağlar. Bu, modelin bir seferde tüm verileri işlememesini ve belleği tüketmemesini sağlar. Ayrıca, daha küçük bir batch size, modelin daha hızlı öğrenmesine de yardımcı olabilir. Ancak çok küçük bir batch size, gradyan hesaplamalarındaki gürültü seviyesini artırabilir ve sonuçta daha yavaş bir eğitim sürecine neden olabilir.

Bu fonksiyonun tam olarak nasıl çalıştığı modelin kütüphanesine göre değişebilir, ancak genel olarak, fit fonksiyonu, modelin öğrenme parametrelerini (ağırlıklar ve biaslar gibi) eğitim verilerine göre ayarlar ve doğru sonuçları vermek için bu parametreleri optimize eder.

In [37]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 30)

Epoch 1/30
250/250 [==============================] - 1s 721us/step - loss: 0.5466 - accuracy: 0.7476
Epoch 2/30
250/250 [==============================] - 0s 720us/step - loss: 0.4604 - accuracy: 0.7960
Epoch 3/30
250/250 [==============================] - 0s 715us/step - loss: 0.4476 - accuracy: 0.7960
Epoch 4/30
250/250 [==============================] - 0s 803us/step - loss: 0.4398 - accuracy: 0.7960
Epoch 5/30
250/250 [==============================] - 0s 727us/step - loss: 0.4349 - accuracy: 0.7960
Epoch 6/30
250/250 [==============================] - 0s 714us/step - loss: 0.4317 - accuracy: 0.7960
Epoch 7/30
250/250 [==============================] - 0s 708us/step - loss: 0.4290 - accuracy: 0.7960
Epoch 8/30
250/250 [==============================] - 0s 717us/step - loss: 0.4264 - accuracy: 0.7960
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.7964
Epoch 10/30
250/250 [==============================] - 0s 803us/step - loss: 0.4211 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Bu kod, eğitilmiş bir yapay sinir ağı modeli kullanılarak yeni bir müşterinin kredi ödeme olasılığını tahmin eder.

İlk olarak, sc.transform fonksiyonu kullanılarak veri normalleştirilir. Bu, verilerin model tarafından kullanılabilmesi için aynı ölçekte olmasını sağlar.

Sonra, normalleştirilmiş veri, yapay sinir ağı modelinin predict fonksiyonuna beslenir. Model, müşterinin kredi ödeme olasılığını tahmin etmek için bu verileri kullanır.

Son olarak, 0.5'ten büyükse 1, küçükse 0 olarak yeniden düzenlenmiş tahmin değeri ekrana yazdırılır. Bu, müşterinin kredi ödeme olasılığının kabaca %50'ye yakın olup olmadığını gösterir. Tahmin değeri, belirli bir kesme değerine göre ikili sınıflandırma olarak belirlenir.

In [59]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 10, 6000000, 2, 1, 1, 5000000]])) > 0.5)

1/1 [==============================] - 0s 28ms/step
[[ True]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

Bu kod, eğitilmiş bir yapay sinir ağı (Artificial Neural Network) modelini kullanarak tahminler yapar ve sonuçları gerçek etiketlerle karşılaştırır.

İkinci satır, y_pred dizisindeki tahmin değerlerini ikili (binary) formda, yani 0.5'ten büyükse 1, küçükse 0 olarak yeniden düzenler. Bu, modelin iki sınıf arasında bir ayrım yaptığı varsayımına dayanır.

Üçüncü satır, np.concatenate fonksiyonunu kullanarak, y_pred ve gerçek test etiketleri y_test arasında birleştirilmiş bir matris oluşturur. Bu matris, her bir örneğin tahmin değeri ve gerçek etiketleri ile birlikte görüntülenir. reshape fonksiyonu, her bir matrisin bir sütunlu bir diziye dönüştürülmesine yardımcı olur.

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

confusion_matrix fonksiyonunu kullanarak gerçek test etiketleri y_test ve tahmin edilen test etiketleri y_pred arasında bir karışıklık matrisi oluşturur. Karışıklık matrisi, sınıflandırma problemlerinde sınıflandırma sonuçlarının doğruluğunu gösteren bir matristir.

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1533   62]
 [ 227  178]]


0.8555